services:
  aarch64-build:
    build: .
    volumes:
      - .:/app
      - cargo-cache:/root/.cargo/registry
      - target-cache:/app/target
    environment:
      - TARGET_LINUX_AARCH64=1
      - CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
      - CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
      - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
      # Model environment variables (can be overridden)
      - EI_MODEL=${EI_MODEL:-}
      - EI_PROJECT_ID=${EI_PROJECT_ID:-}
      - EI_API_KEY=${EI_API_KEY:-}
      - USE_FULL_TFLITE=${USE_FULL_TFLITE:-}
      - EI_ENGINE=${EI_ENGINE:-}
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  cargo-cache:
  target-cache: